export default [
  'debug',
  'debug-dude',
  'moment',
  'normalize.css',
  'ramda',
  'validator',
  'isomorphic-fetch',
  'normalizr',
  'react',
  'react-addons-css-transition-group',
  'react-dnd',
  'react-dom',
  'react-pure-render',
  'redux-simple-router',
  'react-router',
  'history',
  'react-toolbox',
  'react-intl',
  'react-helmet',
  'redux-act',
  'redux-form',
  'redux-promise',
  'redux-logger',
  'reselect',
  // 'recompose',
  // 'rx-recompose',
  // 'rx',
  'classnames',
  // 'react-visibility-sensor',
  // 'form-serialize',
  'serialize-javascript',
  'scroll-behavior',
]
