export default [
  'debug',
  'normalize.css',
  'validator',
  'isomorphic-fetch',
  'react',
  'react-addons-css-transition-group',
  'react-dom',
  'redux-simple-router',
  'react-router',
  'history',
  'react-toolbox',
  'react-helmet',
  'redux-act',
  'redux-form',
  'redux-promise',
  'redux-logger',
  'classnames',
  'react-css-modules',
  'serialize-javascript',
  'scroll-behavior',
  'svg-inline-react',
  'fastclick',
  'fontfaceobserver',
  'socket.io-client',
  // 'howler',
  // 'moment',
  // 'ramda',
  // 'normalizr',
  // 'react-pure-render',
  // 'react-intl',
  // 'reselect',
  // 'react-themeable',
  // 'react-visibility-sensor',
  // 'react-progress-2',
]
